services:
  db:
    image: postgres:15-alpine
    container_name: thenationalfeed-db
    restart: always
    environment:
      POSTGRES_USER: thenationalfeed
      POSTGRES_PASSWORD: thenationalfeed_pass_123
      POSTGRES_DB: thenationalfeed
    ports:
      - '127.0.0.1:5439:5432'
    volumes:
      - thenationalfeed_db_data:/var/lib/postgresql/data

volumes:
  thenationalfeed_db_data:
